services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
