name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: write

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run backend tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Build backend
        run: npm run build
        if: success()

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ github.run_id }}
          restore-keys: |
            npm-cache-

      - name: Package backend (Docker)
        run: |
          docker build -t flag-explorer-backend:latest .
          docker save -o backend.tar flag-explorer-backend:latest
        if: success()

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ./backend/backend.tar
          retention-days: 7 # Retain artifacts longer for better rollback options
        if: success()

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install


      - name: Run frontend tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Build frontend
        run: npm run build
        if: success()

      - name: Package frontend (Zip)
        run: zip -r frontend-build.zip build/
        if: success()

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ github.run_id }}
          restore-keys: |
            npm-cache-

      - name: Package frontend (Docker)
        run: |
          docker build -t flag-explorer-frontend:latest .
          docker save -o frontend.tar flag-explorer-frontend:latest
        if: success()

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: |
            ./frontend/frontend-build.zip
            ./frontend/frontend.tar
          retention-days: 7 # Increased retention for rollback stability
        if: success()
