name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Add permissions for artifact uploads
permissions:
  actions: write

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Update to v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run backend tests
        run: npm test

      - name: Build backend
        run: npm run build

      - name: Clear cache
        uses: actions/cache@v4  # Update to v4
        with:
          path: ~/.npm
          key: force-clear-${{ github.run_id }}

      - name: Package backend (Docker)
        run: |
          docker build -t flag-explorer-backend:latest .
          docker save -o backend.tar flag-explorer-backend:latest

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: backend-artifact
          path: ./backend/backend.tar  # Specify full path relative to root

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Update to v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test

      - name: Build frontend
        run: npm run build

      - name: Package frontend (Zip)
        run: zip -r frontend-build.zip build/

      - name: Clear cache
        uses: actions/cache@v4  # Update to v4
        with:
          path: ~/.npm
          key: force-clear-${{ github.run_id }}

      - name: Package frontend (Docker)
        run: |
          docker build -t flag-explorer-frontend:latest .
          docker save -o frontend.tar flag-explorer-frontend:latest

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: frontend-artifact
          path: |
            ./frontend/frontend-build.zip
            ./frontend/frontend.tar  # Specify full paths relative to root