name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run backend tests
        run: npm test

      - name: Build backend
        run: npm run build
      
      - name: Clear cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: force-clear-${{ github.run_id }}

      - name: Package backend (Docker)
        run: |
          docker build -t flag-explorer-backend:latest .
          docker save -o backend.tar flag-explorer-backend:latest
        working-directory: ./backend

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: backend.tar

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test

      - name: Build frontend
        run: npm run build

      - name: Package frontend (Zip)
        run: zip -r frontend-build.zip build/
        working-directory: ./frontend

      - name: Clear cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: force-clear-${{ github.run_id }}

      - name: Package frontend (Docker)
        run: |
          docker build -t flag-explorer-frontend:latest .
          docker save -o frontend.tar flag-explorer-frontend:latest
        working-directory: ./frontend

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: |
            frontend-build.zip
            frontend.tar